import { RigProject } from '../types';

export interface IndustryTemplate {
  id: string;
  name: string;
  category: 'CORPORATE' | 'BROADCAST' | 'CONCERT_LED' | 'HYBRID_OVERFLOW';
  description: string;
  iconName: string;
  project: RigProject;
}

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: 'corp-dual-imag',
    name: 'Corporate Dual IMAG & Confidence Rig',
    category: 'CORPORATE',
    description: '1 FOH Media Server -> 1x4 Splitter -> 2 Main Stage IMAG Screens + 1 Downstage DSM Monitor',
    iconName: 'Presentation',
    project: {
      version: '1.2.0',
      meta: {
        projectName: 'Corporate Dual IMAG & DSM Rig',
        venue: 'Main Keynote Ballroom',
        author: 'Xteon Pro AV',
        date: new Date().toISOString(),
      },
      nodes: [
        {
          id: 'server-1',
          type: 'deviceNode',
          position: { x: 100, y: 250 },
          data: {
            id: 'server-1',
            label: 'FOH Media Server (ProPresenter)',
            category: 'SOURCE',
            deviceType: 'MEDIA_SERVER',
            customModelName: 'ProPresenter Workstation',
            stageZone: 'FOH Control Booth',
            inputPorts: [],
            outputPorts: [
              { id: 'p-out-1', name: 'HDMI Program Out', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
              { id: 'p-out-2', name: 'DP Multiview Out', type: 'DP_1_4', direction: 'OUTPUT', maxBandwidthGbps: 32.4 },
            ],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'splitter-1',
          type: 'deviceNode',
          position: { x: 450, y: 230 },
          data: {
            id: 'splitter-1',
            label: '1x4 Stage Distribution Amp',
            category: 'DISTRIBUTION',
            deviceType: 'SPLITTER_1X4',
            customModelName: 'Kramer VM-4H2 4K60 Splitter',
            stageZone: 'Stage Left AV Rack',
            inputPorts: [
              { id: 'sp-in-1', name: 'HDMI In', type: 'HDMI_2_0', direction: 'INPUT', maxBandwidthGbps: 18.0 },
            ],
            outputPorts: [
              { id: 'sp-out-1', name: 'Out 1 (Stage Left)', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
              { id: 'sp-out-2', name: 'Out 2 (Stage Right)', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
              { id: 'sp-out-3', name: 'Out 3 (Downstage DSM)', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
              { id: 'sp-out-4', name: 'Out 4 (Aux Rec)', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
            ],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'tv-1',
          type: 'deviceNode',
          position: { x: 850, y: 80 },
          data: {
            id: 'tv-1',
            label: 'Stage Left IMAG Display',
            category: 'SINK',
            deviceType: 'COMMERCIAL_TV',
            customModelName: 'Samsung 75" QM75B UHD Pro',
            stageZone: 'Stage Left',
            inputPorts: [
              { id: 'tv1-in', name: 'HDMI 1 In', type: 'HDMI_2_0', direction: 'INPUT', maxBandwidthGbps: 18.0 },
            ],
            outputPorts: [],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'tv-2',
          type: 'deviceNode',
          position: { x: 850, y: 250 },
          data: {
            id: 'tv-2',
            label: 'Stage Right IMAG Display',
            category: 'SINK',
            deviceType: 'COMMERCIAL_TV',
            customModelName: 'Samsung 75" QM75B UHD Pro',
            stageZone: 'Stage Right',
            inputPorts: [
              { id: 'tv2-in', name: 'HDMI 1 In', type: 'HDMI_2_0', direction: 'INPUT', maxBandwidthGbps: 18.0 },
            ],
            outputPorts: [],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'tv-3',
          type: 'deviceNode',
          position: { x: 850, y: 420 },
          data: {
            id: 'tv-3',
            label: 'Downstage Confidence (DSM)',
            category: 'SINK',
            deviceType: 'CONFIDENCE_MONITOR',
            customModelName: 'LG 55" UltraHD DSM',
            stageZone: 'Downstage Center',
            inputPorts: [
              { id: 'tv3-in', name: 'HDMI 1 In', type: 'HDMI_2_0', direction: 'INPUT', maxBandwidthGbps: 18.0 },
            ],
            outputPorts: [],
            resolution: { width: 1920, height: 1080 },
            refreshRateHz: 60,
          },
        },
      ],
      edges: [
        {
          id: 'e-server-splitter',
          source: 'server-1',
          target: 'splitter-1',
          sourceHandle: 'p-out-1',
          targetHandle: 'sp-in-1',
          data: {
            id: 'e-server-splitter',
            sourceNodeId: 'server-1',
            sourcePortId: 'p-out-1',
            targetNodeId: 'splitter-1',
            targetPortId: 'sp-in-1',
            cableType: 'FIBER_HDMI',
            lengthMeters: 30,
            calculatedBandwidthGbps: 18.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-split-tv1',
          source: 'splitter-1',
          target: 'tv-1',
          sourceHandle: 'sp-out-1',
          targetHandle: 'tv1-in',
          data: {
            id: 'e-split-tv1',
            sourceNodeId: 'splitter-1',
            sourcePortId: 'sp-out-1',
            targetNodeId: 'tv-1',
            targetPortId: 'tv1-in',
            cableType: 'HDMI_2_0',
            lengthMeters: 10,
            calculatedBandwidthGbps: 18.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-split-tv2',
          source: 'splitter-1',
          target: 'tv-2',
          sourceHandle: 'sp-out-2',
          targetHandle: 'tv2-in',
          data: {
            id: 'e-split-tv2',
            sourceNodeId: 'splitter-1',
            sourcePortId: 'sp-out-2',
            targetNodeId: 'tv-2',
            targetPortId: 'tv2-in',
            cableType: 'HDMI_2_0',
            lengthMeters: 15,
            calculatedBandwidthGbps: 18.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-split-tv3',
          source: 'splitter-1',
          target: 'tv-3',
          sourceHandle: 'sp-out-3',
          targetHandle: 'tv3-in',
          data: {
            id: 'e-split-tv3',
            sourceNodeId: 'splitter-1',
            sourcePortId: 'sp-out-3',
            targetNodeId: 'tv-3',
            targetPortId: 'tv3-in',
            cableType: 'HDMI_2_0',
            lengthMeters: 10,
            calculatedBandwidthGbps: 4.5,
            status: 'VALID',
          },
        },
      ],
    },
  },
  {
    id: 'broadcast-4cam',
    name: '4-Camera Studio Broadcast Flypack',
    category: 'BROADCAST',
    description: '4x 12G-SDI Studio Cameras -> Production Switcher -> HyperDeck Recorder + Multiview',
    iconName: 'Video',
    project: {
      version: '1.2.0',
      meta: {
        projectName: '4-Camera Live Broadcast Flypack',
        venue: 'Broadcast Studio A',
        author: 'Xteon Pro AV',
        date: new Date().toISOString(),
      },
      nodes: [
        {
          id: 'cam-1',
          type: 'deviceNode',
          position: { x: 80, y: 80 },
          data: {
            id: 'cam-1',
            label: 'Cam 1 (Wide Center)',
            category: 'SOURCE',
            deviceType: 'CAMERA_SDI',
            customModelName: 'Blackmagic URSA Broadcast G2',
            stageZone: 'Front Center',
            inputPorts: [],
            outputPorts: [{ id: 'cam1-out', name: '12G-SDI Out', type: 'SDI_12G', direction: 'OUTPUT', maxBandwidthGbps: 12.0 }],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'cam-2',
          type: 'deviceNode',
          position: { x: 80, y: 220 },
          data: {
            id: 'cam-2',
            label: 'Cam 2 (Host Tight)',
            category: 'SOURCE',
            deviceType: 'CAMERA_SDI',
            customModelName: 'Blackmagic Studio Camera 4K Pro',
            stageZone: 'Stage Left',
            inputPorts: [],
            outputPorts: [{ id: 'cam2-out', name: '12G-SDI Out', type: 'SDI_12G', direction: 'OUTPUT', maxBandwidthGbps: 12.0 }],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'cam-3',
          type: 'deviceNode',
          position: { x: 80, y: 360 },
          data: {
            id: 'cam-3',
            label: 'Cam 3 (Guest / Audience)',
            category: 'SOURCE',
            deviceType: 'CAMERA_SDI',
            customModelName: 'Blackmagic Studio Camera 4K Pro',
            stageZone: 'Stage Right',
            inputPorts: [],
            outputPorts: [{ id: 'cam3-out', name: '12G-SDI Out', type: 'SDI_12G', direction: 'OUTPUT', maxBandwidthGbps: 12.0 }],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'cam-4',
          type: 'deviceNode',
          position: { x: 80, y: 500 },
          data: {
            id: 'cam-4',
            label: 'Cam 4 (Robotic PTZ)',
            category: 'SOURCE',
            deviceType: 'CAMERA_PTZ',
            customModelName: 'BirdDog P400 4K NDI/SDI',
            stageZone: 'Stage Truss Overhead',
            inputPorts: [],
            outputPorts: [{ id: 'cam4-out', name: '12G-SDI Out', type: 'SDI_12G', direction: 'OUTPUT', maxBandwidthGbps: 12.0 }],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'switcher-atem',
          type: 'deviceNode',
          position: { x: 450, y: 250 },
          data: {
            id: 'switcher-atem',
            label: 'Vision Switcher (ATEM 4K)',
            category: 'SWITCHER',
            deviceType: 'PRODUCTION_SWITCHER',
            customModelName: 'Blackmagic ATEM 1 M/E Constellation 4K',
            stageZone: 'Video Control Desk',
            inputPorts: [
              { id: 'sw-in-1', name: 'SDI In 1', type: 'SDI_12G', direction: 'INPUT', maxBandwidthGbps: 12.0 },
              { id: 'sw-in-2', name: 'SDI In 2', type: 'SDI_12G', direction: 'INPUT', maxBandwidthGbps: 12.0 },
              { id: 'sw-in-3', name: 'SDI In 3', type: 'SDI_12G', direction: 'INPUT', maxBandwidthGbps: 12.0 },
              { id: 'sw-in-4', name: 'SDI In 4', type: 'SDI_12G', direction: 'INPUT', maxBandwidthGbps: 12.0 },
            ],
            outputPorts: [
              { id: 'sw-out-pgm', name: 'PGM 1 Out', type: 'SDI_12G', direction: 'OUTPUT', maxBandwidthGbps: 12.0 },
              { id: 'sw-out-mv', name: 'Multiview Out', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
            ],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'recorder-1',
          type: 'deviceNode',
          position: { x: 850, y: 160 },
          data: {
            id: 'recorder-1',
            label: 'HyperDeck 4K Master Recorder',
            category: 'SOURCE',
            deviceType: 'PLAYBACK_RECORDER',
            customModelName: 'Blackmagic HyperDeck Studio 4K Pro',
            stageZone: 'Engineering Rack',
            inputPorts: [{ id: 'rec-in', name: '12G-SDI In', type: 'SDI_12G', direction: 'INPUT', maxBandwidthGbps: 12.0 }],
            outputPorts: [],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'multiview-disp',
          type: 'deviceNode',
          position: { x: 850, y: 360 },
          data: {
            id: 'multiview-disp',
            label: 'Director Multiview Monitor',
            category: 'SINK',
            deviceType: 'STUDIO_MULTIVIEW',
            customModelName: 'Dell UltraSharp 43" 4K',
            stageZone: 'Director Station',
            inputPorts: [{ id: 'mv-in', name: 'HDMI In', type: 'HDMI_2_0', direction: 'INPUT', maxBandwidthGbps: 18.0 }],
            outputPorts: [],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
      ],
      edges: [
        {
          id: 'e-c1-sw',
          source: 'cam-1',
          target: 'switcher-atem',
          sourceHandle: 'cam1-out',
          targetHandle: 'sw-in-1',
          data: {
            id: 'e-c1-sw',
            sourceNodeId: 'cam-1',
            sourcePortId: 'cam1-out',
            targetNodeId: 'switcher-atem',
            targetPortId: 'sw-in-1',
            cableType: 'SDI_12G',
            lengthMeters: 40,
            calculatedBandwidthGbps: 12.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-c2-sw',
          source: 'cam-2',
          target: 'switcher-atem',
          sourceHandle: 'cam2-out',
          targetHandle: 'sw-in-2',
          data: {
            id: 'e-c2-sw',
            sourceNodeId: 'cam-2',
            sourcePortId: 'cam2-out',
            targetNodeId: 'switcher-atem',
            targetPortId: 'sw-in-2',
            cableType: 'SDI_12G',
            lengthMeters: 30,
            calculatedBandwidthGbps: 12.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-c3-sw',
          source: 'cam-3',
          target: 'switcher-atem',
          sourceHandle: 'cam3-out',
          targetHandle: 'sw-in-3',
          data: {
            id: 'e-c3-sw',
            sourceNodeId: 'cam-3',
            sourcePortId: 'cam3-out',
            targetNodeId: 'switcher-atem',
            targetPortId: 'sw-in-3',
            cableType: 'SDI_12G',
            lengthMeters: 30,
            calculatedBandwidthGbps: 12.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-c4-sw',
          source: 'cam-4',
          target: 'switcher-atem',
          sourceHandle: 'cam4-out',
          targetHandle: 'sw-in-4',
          data: {
            id: 'e-c4-sw',
            sourceNodeId: 'cam-4',
            sourcePortId: 'cam4-out',
            targetNodeId: 'switcher-atem',
            targetPortId: 'sw-in-4',
            cableType: 'SDI_12G',
            lengthMeters: 50,
            calculatedBandwidthGbps: 12.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-sw-rec',
          source: 'switcher-atem',
          target: 'recorder-1',
          sourceHandle: 'sw-out-pgm',
          targetHandle: 'rec-in',
          data: {
            id: 'e-sw-rec',
            sourceNodeId: 'switcher-atem',
            sourcePortId: 'sw-out-pgm',
            targetNodeId: 'recorder-1',
            targetPortId: 'rec-in',
            cableType: 'SDI_12G',
            lengthMeters: 5,
            calculatedBandwidthGbps: 12.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-sw-mv',
          source: 'switcher-atem',
          target: 'multiview-disp',
          sourceHandle: 'sw-out-mv',
          targetHandle: 'mv-in',
          data: {
            id: 'e-sw-mv',
            sourceNodeId: 'switcher-atem',
            sourcePortId: 'sw-out-mv',
            targetNodeId: 'multiview-disp',
            targetPortId: 'mv-in',
            cableType: 'HDMI_2_0',
            lengthMeters: 3,
            calculatedBandwidthGbps: 18.0,
            status: 'VALID',
          },
        },
      ],
    },
  },
  {
    id: 'led-wall-arena',
    name: 'Arena LED Video Wall Processor Rig',
    category: 'CONCERT_LED',
    description: 'Media Server DP 1.4 -> NovaStar MX40 Screen Processor -> Main 2.6mm LED Wall + Left/Right Banners',
    iconName: 'Tv',
    project: {
      version: '1.2.0',
      meta: {
        projectName: 'Arena LED Video Wall & Processor Rig',
        venue: 'Metropolis Arena',
        author: 'Xteon Pro AV',
        date: new Date().toISOString(),
      },
      nodes: [
        {
          id: 'media-disguise',
          type: 'deviceNode',
          position: { x: 80, y: 220 },
          data: {
            id: 'media-disguise',
            label: 'Media Server (disguise vx4)',
            category: 'SOURCE',
            deviceType: 'MEDIA_SERVER',
            customModelName: 'disguise vx 4 Pro Media Server',
            stageZone: 'FOH Media Platform',
            inputPorts: [],
            outputPorts: [
              { id: 'vx-out-1', name: 'DP 1.4 Out 1 (Main Wall)', type: 'DP_1_4', direction: 'OUTPUT', maxBandwidthGbps: 32.4 },
              { id: 'vx-out-2', name: 'DP 1.4 Out 2 (Side Wings)', type: 'DP_1_4', direction: 'OUTPUT', maxBandwidthGbps: 32.4 },
            ],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'barco-s3',
          type: 'deviceNode',
          position: { x: 450, y: 220 },
          data: {
            id: 'barco-s3',
            label: 'NovaStar MX40 Pro UHD Processor',
            category: 'PROCESSOR',
            deviceType: 'NOVASTAR_MX40_PRO',
            customModelName: 'NovaStar MX40 Pro LED Controller',
            stageZone: 'Dimmer Beach / Video Rack',
            inputPorts: [
              { id: 's3-in-1', name: 'DP In 1', type: 'DP_1_4', direction: 'INPUT', maxBandwidthGbps: 32.4 },
              { id: 's3-in-2', name: 'DP In 2', type: 'DP_1_4', direction: 'INPUT', maxBandwidthGbps: 32.4 },
            ],
            outputPorts: [
              { id: 's3-out-main', name: 'Fiber Out 1 (Main Wall)', type: 'FIBER_HDMI', direction: 'OUTPUT', maxBandwidthGbps: 48.0 },
              { id: 's3-out-wings', name: 'Fiber Out 2 (Side Wings)', type: 'FIBER_HDMI', direction: 'OUTPUT', maxBandwidthGbps: 48.0 },
            ],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'led-main-wall',
          type: 'deviceNode',
          position: { x: 880, y: 120 },
          data: {
            id: 'led-main-wall',
            label: 'Main Stage Center LED Wall',
            category: 'SINK',
            deviceType: 'LED_WALL',
            customModelName: 'ROE Visual Ruby 2.6mm (3840x2160 UHD)',
            stageZone: 'Upstage Center Wall',
            inputPorts: [{ id: 'led-main-in', name: 'Fiber Optic In', type: 'FIBER_HDMI', direction: 'INPUT', maxBandwidthGbps: 48.0 }],
            outputPorts: [],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'led-side-wings',
          type: 'deviceNode',
          position: { x: 880, y: 340 },
          data: {
            id: 'led-side-wings',
            label: 'Left & Right LED Columns',
            category: 'SINK',
            deviceType: 'LED_WALL',
            customModelName: 'ROE Visual Black Pearl 3.9mm Column Banners',
            stageZone: 'Stage Left & Right Wings',
            inputPorts: [{ id: 'led-wings-in', name: 'Fiber Optic In', type: 'FIBER_HDMI', direction: 'INPUT', maxBandwidthGbps: 48.0 }],
            outputPorts: [],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
      ],
      edges: [
        {
          id: 'e-vx-s3-1',
          source: 'media-disguise',
          target: 'barco-s3',
          sourceHandle: 'vx-out-1',
          targetHandle: 's3-in-1',
          data: {
            id: 'e-vx-s3-1',
            sourceNodeId: 'media-disguise',
            sourcePortId: 'vx-out-1',
            targetNodeId: 'barco-s3',
            targetPortId: 's3-in-1',
            cableType: 'DP_1_4',
            lengthMeters: 5,
            calculatedBandwidthGbps: 32.4,
            status: 'VALID',
          },
        },
        {
          id: 'e-vx-s3-2',
          source: 'media-disguise',
          target: 'barco-s3',
          sourceHandle: 'vx-out-2',
          targetHandle: 's3-in-2',
          data: {
            id: 'e-vx-s3-2',
            sourceNodeId: 'media-disguise',
            sourcePortId: 'vx-out-2',
            targetNodeId: 'barco-s3',
            targetPortId: 's3-in-2',
            cableType: 'DP_1_4',
            lengthMeters: 5,
            calculatedBandwidthGbps: 32.4,
            status: 'VALID',
          },
        },
        {
          id: 'e-s3-main',
          source: 'barco-s3',
          target: 'led-main-wall',
          sourceHandle: 's3-out-main',
          targetHandle: 'led-main-in',
          data: {
            id: 'e-s3-main',
            sourceNodeId: 'barco-s3',
            sourcePortId: 's3-out-main',
            targetNodeId: 'led-main-wall',
            targetPortId: 'led-main-in',
            cableType: 'FIBER_HDMI',
            lengthMeters: 80,
            calculatedBandwidthGbps: 48.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-s3-wings',
          source: 'barco-s3',
          target: 'led-side-wings',
          sourceHandle: 's3-out-wings',
          targetHandle: 'led-wings-in',
          data: {
            id: 'e-s3-wings',
            sourceNodeId: 'barco-s3',
            sourcePortId: 's3-out-wings',
            targetNodeId: 'led-side-wings',
            targetPortId: 'led-wings-in',
            cableType: 'FIBER_HDMI',
            lengthMeters: 80,
            calculatedBandwidthGbps: 48.0,
            status: 'VALID',
          },
        },
      ],
    },
  },
  {
    id: 'hybrid-overflow-glidex',
    name: 'Hybrid Overflow & ASUS GlideX Wireless Rig',
    category: 'HYBRID_OVERFLOW',
    description: 'Workstation -> HDBaseT Cat6 Extenders -> Overflow Room + ASUS GlideX Wireless Tablet & Stage Displays',
    iconName: 'Wifi',
    project: {
      version: '1.2.0',
      meta: {
        projectName: 'Hybrid Overflow & Wireless Mobile Rig',
        venue: 'Conference Center Hall B',
        author: 'Xteon Pro AV',
        date: new Date().toISOString(),
      },
      nodes: [
        {
          id: 'host-pc',
          type: 'deviceNode',
          position: { x: 80, y: 220 },
          data: {
            id: 'host-pc',
            label: 'Host Workstation & Media Hub',
            category: 'SOURCE',
            deviceType: 'LAPTOP',
            customModelName: 'Production Laptop',
            stageZone: 'FOH Control Desk',
            inputPorts: [],
            outputPorts: [
              { id: 'host-hdmi', name: 'HDMI 2.0 Out', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
              { id: 'host-wifi', name: 'ASUS GlideX Wireless Beam', type: 'WIRELESS', direction: 'OUTPUT', maxBandwidthGbps: 10.0 },
            ],
            resolution: { width: 1920, height: 1080 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'hdbt-tx',
          type: 'deviceNode',
          position: { x: 450, y: 120 },
          data: {
            id: 'hdbt-tx',
            label: 'HDBaseT Cat6A Transmitter (TX)',
            category: 'CONVERTER',
            deviceType: 'HDBASET_TX',
            customModelName: 'Blustream HEX100CS-TX 4K Extender',
            stageZone: 'FOH Rack',
            inputPorts: [
              { id: 'tx-hdmi-in', name: 'HDMI In', type: 'HDMI_2_0', direction: 'INPUT', maxBandwidthGbps: 18.0 },
            ],
            outputPorts: [
              { id: 'tx-cat6-out', name: 'HDBaseT Cat6A Out', type: 'HDBASET_CAT6', direction: 'OUTPUT', maxBandwidthGbps: 10.2 },
            ],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'hdbt-rx',
          type: 'deviceNode',
          position: { x: 780, y: 120 },
          data: {
            id: 'hdbt-rx',
            label: 'HDBaseT Cat6A Receiver (RX)',
            category: 'CONVERTER',
            deviceType: 'HDBASET_RX',
            customModelName: 'Blustream HEX100CS-RX 4K Extender',
            stageZone: 'Overflow Room Rack',
            inputPorts: [
              { id: 'rx-cat6-in', name: 'HDBaseT Cat6A In', type: 'HDBASET_CAT6', direction: 'INPUT', maxBandwidthGbps: 10.2 },
            ],
            outputPorts: [
              { id: 'rx-hdmi-out', name: 'HDMI Out', type: 'HDMI_2_0', direction: 'OUTPUT', maxBandwidthGbps: 18.0 },
            ],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'overflow-tv',
          type: 'deviceNode',
          position: { x: 1100, y: 120 },
          data: {
            id: 'overflow-tv',
            label: 'Overflow Room 85" Display',
            category: 'SINK',
            deviceType: 'COMMERCIAL_TV',
            customModelName: 'Sony BRAVIA FW-85BZ40H 4K',
            stageZone: 'Overflow Hallway',
            inputPorts: [{ id: 'of-tv-in', name: 'HDMI 1 In', type: 'HDMI_2_0', direction: 'INPUT', maxBandwidthGbps: 18.0 }],
            outputPorts: [],
            resolution: { width: 3840, height: 2160 },
            refreshRateHz: 60,
          },
        },
        {
          id: 'glidex-mobile',
          type: 'deviceNode',
          position: { x: 780, y: 340 },
          data: {
            id: 'glidex-mobile',
            label: 'Mobile Director Tablet (ASUS GlideX)',
            category: 'SINK',
            deviceType: 'CONFIDENCE_MONITOR',
            customModelName: 'ROG Phone / Tablet Wireless Display',
            stageZone: 'Roaming Mobile Stage Director',
            inputPorts: [{ id: 'glidex-in', name: 'Wireless Stream In', type: 'WIRELESS', direction: 'INPUT', maxBandwidthGbps: 10.0 }],
            outputPorts: [],
            resolution: { width: 1920, height: 1080 },
            refreshRateHz: 60,
          },
        },
      ],
      edges: [
        {
          id: 'e-host-tx',
          source: 'host-pc',
          target: 'hdbt-tx',
          sourceHandle: 'host-hdmi',
          targetHandle: 'tx-hdmi-in',
          data: {
            id: 'e-host-tx',
            sourceNodeId: 'host-pc',
            sourcePortId: 'host-hdmi',
            targetNodeId: 'hdbt-tx',
            targetPortId: 'tx-hdmi-in',
            cableType: 'HDMI_2_0',
            lengthMeters: 2,
            calculatedBandwidthGbps: 18.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-tx-rx',
          source: 'hdbt-tx',
          target: 'hdbt-rx',
          sourceHandle: 'tx-cat6-out',
          targetHandle: 'rx-cat6-in',
          data: {
            id: 'e-tx-rx',
            sourceNodeId: 'hdbt-tx',
            sourcePortId: 'tx-cat6-out',
            targetNodeId: 'hdbt-rx',
            targetPortId: 'rx-cat6-in',
            cableType: 'HDBASET_CAT6',
            lengthMeters: 75,
            calculatedBandwidthGbps: 10.2,
            status: 'VALID',
          },
        },
        {
          id: 'e-rx-tv',
          source: 'hdbt-rx',
          target: 'overflow-tv',
          sourceHandle: 'rx-hdmi-out',
          targetHandle: 'of-tv-in',
          data: {
            id: 'e-rx-tv',
            sourceNodeId: 'hdbt-rx',
            sourcePortId: 'rx-hdmi-out',
            targetNodeId: 'overflow-tv',
            targetPortId: 'of-tv-in',
            cableType: 'HDMI_2_0',
            lengthMeters: 5,
            calculatedBandwidthGbps: 18.0,
            status: 'VALID',
          },
        },
        {
          id: 'e-host-glidex',
          source: 'host-pc',
          target: 'glidex-mobile',
          sourceHandle: 'host-wifi',
          targetHandle: 'glidex-in',
          data: {
            id: 'e-host-glidex',
            sourceNodeId: 'host-pc',
            sourcePortId: 'host-wifi',
            targetNodeId: 'glidex-mobile',
            targetPortId: 'glidex-in',
            cableType: 'WIRELESS',
            lengthMeters: 15,
            calculatedBandwidthGbps: 5.0,
            status: 'VALID',
          },
        },
      ],
    },
  },
];
